/**
 * Response types for the ten secondary pages.
 *
 * These are transcribed from `docs/API_SHAPES.md`, which is generated by probing the
 * RUNNING API rather than from the written contract. That distinction matters: the
 * first build round typed `meta.highlights` as `{regionId, regionName}` objects when
 * the API actually emits plain strings, and because `"North".regionName` is silently
 * `undefined` rather than a type error, all three Regional StatTiles rendered an
 * em-dash with nothing failing loudly.
 *
 * If you need a field that is not here, probe the endpoint and add it — do not guess.
 */

// ---------------------------------------------------------------------------
// Products (SRS §11)
// ---------------------------------------------------------------------------
export interface Product {
  drugId: number;
  drugCode: string;
  drugName: string;
  genericName: string;
  taId: number;
  taName: string;
  unitPrice: number;
  dosageForm: string;
  strength: string;
  unitsSold: number;
  revenue: number;
  rxVolume: number;
  growthPct: number;
  marketSharePct: number;
}

export interface ProductCompetitor {
  competitorDrugId: number;
  competitorName: string;
  companyName: string;
  unitPrice: number;
  competitorSharePct: number;
}

export interface ProductDetail extends Product {
  competitors: ProductCompetitor[];
}

export interface TrendPoint {
  period: string;
  revenue: number;
  units: number;
}

export interface ProductRegionalRow {
  regionId: number;
  regionName: string;
  revenue: number;
  units: number;
  marketSharePct: number;
}

// ---------------------------------------------------------------------------
// Sales representatives (SRS §14)
// ---------------------------------------------------------------------------
export interface SalesRep {
  repId: number;
  repCode: string;
  fullName: string;
  regionId: number;
  regionName: string;
  territory: string;
  revenue: number;
  target: number;
  achievementPct: number;
  visits: number;
  hcpCount: number;
  rank: number;
}

export interface RepPanelHcp {
  hcpId: number;
  hcpCode: string;
  fullName: string;
  specialty: string;
  hospital: string;
  regionName: string;
  potentialScore: number | null;
  priority: string | null;
  lastVisitDate: string | null;
}

/** HCP score components, weighted per SRS §13 (40/25/15/10/10). */
export interface ScoreComponents {
  rxVolume: number;
  rxGrowth: number;
  engagement: number;
  taRelevance: number;
  competitorOpportunity: number;
}

export interface RecommendedHcp {
  hcpId: number;
  hcpName: string;
  totalScore: number;
  priority: "HIGH" | "MEDIUM" | "LOW";
  components: ScoreComponents;
  weights: ScoreComponents;
  reasons: string[];
  /** States that the score is a COMMERCIAL prioritisation, not a medical judgement. */
  disclaimer: string;
}

// ---------------------------------------------------------------------------
// Regions (SRS §15)
// ---------------------------------------------------------------------------
export interface Region {
  regionId: number;
  regionName: string;
  zoneHead: string;
  revenue: number;
  growthPct: number;
  marketSharePct: number;
  prescriptions: number;
  hcpCount: number;
  repCount: number;
}

export type DrilldownLevel = "city" | "ta" | "product";

export interface DrilldownRow {
  id: number;
  name: string;
  revenue: number;
  units: number;
}

// ---------------------------------------------------------------------------
// Competitors
// ---------------------------------------------------------------------------
export interface Competitor {
  competitorId: number;
  companyName: string;
  hqCountry: string;
  drugCount: number;
  avgSharePct: number;
}

export interface MarketSharePoint {
  period: string;
  ourSharePct: number;
  competitorSharePct: number;
}

// ---------------------------------------------------------------------------
// Inventory
// ---------------------------------------------------------------------------
export interface InventoryRow {
  drugId: number;
  drugName: string;
  regionId: number;
  regionName: string;
  snapshotMonth: string;
  closingStock: number;
  unitsOut: number;
  coverMonths: number;
  stockoutDays: number;
  riskFlag: string;
}

// ---------------------------------------------------------------------------
// Forecasting (SRS §23) — always present as an ESTIMATE, never a guarantee
// ---------------------------------------------------------------------------
export type ForecastEntityType = "COMPANY" | "DRUG" | "REGION" | "TA";

export interface ForecastHistoryPoint {
  period: string;
  value: number;
}

export interface ForecastPoint {
  period: string;
  predicted: number;
  lower: number;
  upper: number;
}

export interface ForecastResult {
  entityType: ForecastEntityType;
  entityId: number | null;
  horizon: number;
  history: ForecastHistoryPoint[];
  forecast: ForecastPoint[];
  model: string;
  /** Backtest error. Render it so users can judge confidence. */
  mape: number | null;
}

// ---------------------------------------------------------------------------
// Alerts & anomalies (SRS §24)
// ---------------------------------------------------------------------------
export type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";

export interface AlertItem {
  alertId: number;
  alertType: string;
  severity: Severity;
  title: string;
  message: string;
  entityType: string | null;
  entityId: number | null;
  audienceRole: string;
  isRead: boolean;
  createdAt: string;
}

export interface AnomalyItem {
  anomalyId: number;
  entityType: string;
  entityId: number | null;
  entityName: string | null;
  periodMonth: string;
  metric: string;
  actual: number;
  expected: number;
  deviationPct: number;
  zScore: number;
  severity: Severity;
  direction: "DROP" | "SPIKE";
  detectedAt: string;
}

// ---------------------------------------------------------------------------
// Recommendations & root cause (SRS §25, §26)
// ---------------------------------------------------------------------------
export interface Recommendation {
  recType: string;
  title: string;
  rationale: string;
  expectedImpact: string;
  priority: "HIGH" | "MEDIUM" | "LOW";
  confidence: number;
  targetEntityType: string | null;
  targetEntityId: number | null;
}

export type ContributorFactor =
  | "PRESCRIPTION_VOLUME"
  | "HCP_ENGAGEMENT"
  | "COMPETITOR_SHARE"
  | "INVENTORY"
  | "PRICE_DISCOUNT";

export interface RootCauseContributor {
  factor: ContributorFactor;
  label: string;
  changePct: number;
  /** Share of the headline move attributed here; the five sum to ~100. */
  contributionPct: number;
  direction: "NEGATIVE" | "POSITIVE";
  detail: string;
}

export interface RootCauseResult {
  headline: {
    metric: string;
    changePct: number;
    direction: "DROP" | "SPIKE";
    current: number;
    previous: number;
    periodLabel: string;
  };
  contributors: RootCauseContributor[];
  recommendations: Recommendation[];
  confidence: number;
}
